---
# Entrypoint

- name: configure Raspberry Pi
  hosts: pi
  remote_user: pi

  roles:
    - { role: 'pi', tags: 'pi' }
    - { role: 'dyndns', tags: 'dyndns' }
    - { role: 'syncthing', tags: 'syncthing' }

- name: configure local machine
  hosts: local
  tasks:
    - import_role:
        name: syncthing
      tags: 'syncthing'
      when: ansible_hostname == "pluto"
