---
# Entrypoint

- name: configure Raspberry Pi
  hosts: pi
  remote_user: pi

  roles:
    - { role: "pi", tags: ["pi"] }
    - { role: "dyndns", tags: ["dyndns"] }
    - { role: "syncthing", tags: ["syncthing"] }
    - { role: "caddy", tags: ["caddy"] }

- name: configure local machine
  hosts: local
  tasks:
    - name: import syncthing role
      import_role:
        name: syncthing
      tags: "syncthing"
      when: ansible_hostname == "pluto"
