---
- name: Ensure dependencies are installed.
  apt:
    name:
      - debian-keyring
      - debian-archive-keyring
      - apt-transport-https
      - gnupg2
      - curl
    state: present
  become: yes

- name: "add key"
  apt_key:
    url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
    id: 65760C51EDEA2017CEA2CA15155B6D79CA56EA34
    state: present
  become: yes

- name: "add apt repository"
  apt_repository:
    repo: "{{ item }}"
    state: present
    filename: caddy-stable
  loop:
    - "deb https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main"
    - "deb-src https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main"
  become: yes

- name: "install caddy"
  apt:
    name: caddy
    state: present
    update_cache: yes
  become: yes
  notify: restart caddy

- name: configure
  copy:
    src: "Caddyfile"
    dest: "/etc/caddy/Caddyfile"
  become: yes
