---
- name: check if caddy executable is present
  shell: "which caddy"
  register: result
  ignore_errors: true

- import_tasks: install.yml
  when: result.rc != 0

- name: configure
  copy:
    src: "Caddyfile"
    dest: "/etc/caddy/Caddyfile"
    mode: u=rw,g=rw,o=r
  become: yes
  notify: reload caddy

- name: copy index page
  copy:
    src: index.html
    dest: /home/pi/public_html/index.html