---

- name: "ensure transmission-daemon installed"
  package:
    name: transmission-daemon
    state: present

- name: "ensure transmission-daemon stopped"
  service:
    name: transmission-daemon
    state: stopped
  become: true

- name: "create required directories"
  file:
    path: "{{ item }}"
    state: directory
    owner: "debian-transmission"
    group: "debian-transmission"
  with_items:
    - "{{ transmission_download_dir }}"
    - "{{ transmission_incomplete_dir }}"
    - "/etc/transmission-daemon"
  become: true

- name: "create settings file"
  template:
    src: settings.json.j2
    dest: "/etc/transmission-daemon/settings.json"
    owner: "debian-transmission"
    group: "debian-transmission"
    mode: 0600
  notify: "reload settings"
  become: true

- name: "ensure transmission-daemon running"
  service:
    name: transmission-daemon
    state: started
  become: true